name: Django CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Adjust to match your project

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r /home/ubuntu/student/student_project_django-main/Student_project/requirements.txt

      - name: Django migrate and collectstatic
        run: |
          source env/bin/activate
          cd Student_project
          python manage.py migrate
          python manage.py collectstatic --noinput

      # Optional: Run tests
      # - name: Run tests
      #   run: |
      #     source env/bin/activate
      #     cd Student_project
      #     python manage.py test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/student_project_django
            git pull origin main
            source env/bin/activate
            pip install -r Student_project/requirements.txt
            cd Student_project
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn  # or whatever you use
