name: Django CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: student/student_project_django-main/Student_project
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r ../requirements.txt

      - name: Run migrations
        working-directory: student/student_project_django-main/Student_project
        run: |
          source env/bin/activate
          python manage.py migrate

      - name: Collect static files
        working-directory: student/student_project_django-main/Student_project
        run: |
          source env/bin/activate
          python manage.py collectstatic --noinput

      # Optional: Add a test step if you have tests
      # - name: Run tests
      #   working-directory: student/student_project_django-main/Student_project
      #   run: |
      #     source env/bin/activate
      #     python manage.py test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/student/student_project_django-main/Student_project
            git pull origin main
            source env/bin/activate
            pip install -r ../requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl reload nginx

