name: Django CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install django-countries
          pip install -r student_project_django-main/Student_project/requirements.txt

      - name: Run migrations
        run: |
          source env/bin/activate
          cd student_project_django-main/Student_project
          python manage.py migrate

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/student/student_project_django-main/Student_project

            # Install venv if not already
            sudo apt-get update
            sudo apt-get install -y python3-venv

            # Create venv if not exists
            [ ! -d env ] && python3 -m venv env

            source env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py runserver 0.0.0.0:8000
